---
apiVersion: v1
kind: Secret
metadata:
  name: script
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: ubuntu-upgrade
  namespace: system-upgrade
spec:
  concurrency: 1
  postCompleteDelay: "10m"
  version: "06.2026"
  window:
    days:
     - "6"
     - "0"
    startTime: "10:00:00"
    endTime: "23:00:00"
    timeZone: "Asia/Yekaterinburg"
  nodeSelector:
    matchExpressions:
      - key: plan.upgrade.cattle.io/ubuntu
        operator: Exists
  serviceAccountName: system-upgrade
  cordon: false
#  drain:
#    force: true
#    ignoreDaemonSets: true
#    deleteEmptyDirData: true
  secrets:
    - name: script
      path: /host/run/system-upgrade/secrets/script
  upgrade:
    image: ubuntu:24.04
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/script/upgrade.sh"]
