ansible_user: 'pi'
cluster_name: kubernetes
dns_domain: 'cluster.local'
kube_service_subnets: "10.96.0.0/23"
kube_pods_subnet: "10.95.0.0/22"
loadbalancer_apiserver_port: 8443
loadbalancer_apiserver_address: 'cluster-endpoint'
kubernetes_pkg_version: '1.34.10-1.1'
containerd_pkg_version: '2.3.3-1~ubuntu.24.04~noble'
haproxy_pkg_version: '2.8.16-0ubuntu0.24.04.3'
cri_tools_pkg_version: '1.34.0-1.1'
sandbox_image: 'registry.k8s.io/pause:3.10.1'
cilium_version: '1.20.1'
flux_version: '2.9.4'
kubeseal_version: '0.39.1'
helm_pkg_version: '4.2.3-1'
cilium_cli_version: '0.19.7'
flux_gitlab_repo: orchestration
flux_gitlab_branch: main
flux_gitlab_path: 'clusters/rpi-cluster'
gitlab_user: s045724
kube_config_dir: /etc/kubernetes
kube_cert_dir: "{{ kube_config_dir }}/pki"
kube_manifest_dir: "{{ kube_config_dir }}/manifests"
haproxy_config_dir: /etc/haproxy
containerd_config_dir: /etc/containerd
kubelet_config_dir: /var/lib/kubelet
bin_dir: /usr/local/bin
cri_socket: "unix:///var/run/containerd/containerd.sock"
# os
unattended_upgrades: false
#proxy_address: "socks5h://192.168.1.208:1080"
# irq
irq_affinity: false
# sysctl
sysctl_config:
  net.core.netdev_max_backlog: 8192
  net.core.somaxconn: 4096
  net.core.rmem_max: 67108864
  net.core.wmem_max: 67108864
  net.ipv4.tcp_rmem: 4096 87380 33554432
  net.ipv4.tcp_wmem: 4096 65536 33554432
  net.netfilter.nf_conntrack_max: 131072
  net.netfilter.nf_conntrack_buckets: 32768
  net.ipv4.tcp_max_syn_backlog: 2048
  net.ipv4.tcp_fin_timeout: 15
  net.ipv4.tcp_tw_reuse: 1
# kubelet
kubelet_max_pods: 110
kubelet_pod_pids_limit: -1
kubelet_healthz_port: 10248
kubelet_healthz_bind_address: 127.0.0.1
kubelet_status_update_frequency: 10s
kubelet_fail_swap_on: true
kubelet_authentication_token_webhook: true
kubelet_authorization_mode_webhook: true
kubelet_cgroup_driver: systemd
kubelet_logfiles_max_nr: 5
kubelet_logfiles_max_size: 10Mi
kubelet_rotate_certificates: true
kubelet_rotate_server_certificates: false
kubelet_feature_gates:
  - InPlacePodVerticalScaling=true
kubelet_max_parallel_image_pulls: 2
kubelet_image_gc_high_threshold: 85
kubelet_image_gc_low_threshold: 80
kubelet_image_maximum_gc_age: "168h"
kubelet_event_record_qps: 5
kubelet_shutdown_grace_period: 0s
kubelet_shutdown_grace_period_critical_pods: 0s
kubelet_swap_behavior: UnlimitedSwap
kubelet_streaming_connection_idle_timeout: "4h0m0s"
kube_resolv_conf: "/run/systemd/resolve/resolv.conf"
kubelet_cluster_dns:
  - "{{ kube_service_subnets | ansible.utils.ipaddr('network') | ansible.utils.ipmath(10) }}"
kubelet_eviction_pressure_transition_period: "30s"
eviction_hard:
  memory.available: "100Mi"
  nodefs.available: "10%"
  nodefs.inodesFree: "5%"
  imagefs.available: "15%"
  imagefs.inodesFree: "5%"
# CPU Manager Policy
kubelet_cpu_manager_policy: "static"
kubelet_cpu_manager_policy_options:
  strict-cpu-reservation: "true"
# reservedSystemCPUs option incompatible with cgroup reservations kube_reserved_cgroups,system_reserved_cgroups
kubelet_reserved_system_cpus: "0"
kubelet_cpu_manager_reconcile_period: "5s"
#kubelet_topology_manager_policy: "best-effort"
# Enforce node allocatable settings  
kubelet_enforce_node_allocatable: "pods"
# Kube-reserved settings for Kubernetes components
#kube_reserved_cgroups: "kube.slice"
#kube_reserved_resources:
#  cpu: "200m"
#  memory: "512Mi"
#  ephemeral-storage: "5Gi"
#  pid: "1000"
# System-reserved settings for OS daemons
#system_reserved_cgroups: "system.slice"
system_reserved_resources:
  cpu: "200m"
  memory: "512Mi"
  ephemeral-storage: "5Gi"
  pid: "1000"
