etcd_version: '3.5.31'
etcd_owner: etcd
#etcd_cert_group: root
etcd_data_dir: /var/lib/etcd
etcd_config_dir: /etc/ssl/etcd
etcd_cert_dir: "{{ etcd_config_dir }}/ssl"
etcd_initial_cluster_state: existing
