---
variables:
  ANSIBLE_IMAGE: c8h11no2/ansible:11.4.0-python3.12
  ANSIBLE_HOST_KEY_CHECKING: 'false'
  ANSIBLE_FORCE_COLOR: 'true'

stages:
  - lint
  - deploy

.job__deploy__rules:
  stage: deploy
  image:
    name: $ANSIBLE_IMAGE
  before_script:
    - ansible-galaxy collection install -r ansible/requirements.yml
    - eval $(ssh-agent -s)
    - chmod 400 "$ANSIBLE_SSH_PRIVATE_KEY"
    - ssh-add "$ANSIBLE_SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ls ~/.ssh/
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

.job__lint__rules:
  stage: lint
  image:
    name: $ANSIBLE_IMAGE
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

yaml-lint:
  extends:
    - .job__lint__rules
  script:
    - yamllint -f colored .

ansible-lint:
  extends:
    - .job__lint__rules
  before_script:
    - ansible-galaxy collection install -r ansible/requirements.yml
  script:
    - ansible-lint ansible/

deploy-cluster-dependencies:
  extends:
    - .job__deploy__rules
  script:
    - ansible-playbook ansible/playbooks/cluster_dependencies.yaml -i ansible/inventory/hosts.yaml

deploy-cluster-init:
  extends:
    - .job__deploy__rules
  script:
    - ansible-playbook ansible/playbooks/cluster_init.yaml -i ansible/inventory/hosts.yaml

deploy-fluxcd:
  extends:
    - .job__deploy__rules
  script:
    - ansible-playbook ansible/playbooks/fluxcd.yaml -i ansible/inventory/hosts.yaml

deploy-cluster-join-node:
  extends:
    - .job__deploy__rules
  script:
    - ansible-playbook ansible/playbooks/cluster_join_node.yaml -i ansible/inventory/hosts.yaml
