---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-announcement-policy
  namespace: kube-system
spec:
#  nodeSelector:
#    matchExpressions:
#      - key: node-role.kubernetes.io/control-plane
#        operator: Exists
  interfaces:
    - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: loadbalancer-ips
  namespace: kube-system
spec:
  blocks:
  - cidr: "192.168.31.10/29"
