---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ./cilium/loadbalancer.yaml
  - ./prometheus/alertmanager-sealed.yaml
  - ./prometheus/prom-stack-credentials-sealed.yaml
  - ./gateway-api/v1.4.1/crd/gateway.networking.k8s.io_backendtlspolicies.yaml
  - ./gateway-api/v1.4.1/crd/gateway.networking.k8s.io_gatewayclasses.yaml
  - ./gateway-api/v1.4.1/crd/gateway.networking.k8s.io_gateways.yaml
  - ./gateway-api/v1.4.1/crd/gateway.networking.k8s.io_grpcroutes.yaml
  - ./gateway-api/v1.4.1/crd/gateway.networking.k8s.io_httproutes.yaml
  - ./gateway-api/v1.4.1/crd/gateway.networking.k8s.io_referencegrants.yaml
