---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secret-files
  namespace: monitoring
spec:
  encryptedData:
    telegram-bot-token: AgAmw7X23An8rXjU01vSUps4OK1LipGXZcgw/ME/HaaprdAdan7/VTN0LmBstAKiLK7NZT6IFHgeuGAaSODSlzJLBCaOJQvEnvdi0P7zLdsUHicG3ZkqBZX2nOhIiyFKEcv+wVWSCZX4tY2Z0rTGqRYrkGhj1HhdYLcioQsPRYE2OoFbPDvJqPfvNc71ieNYaBiAGpwO+21Jy6evF7bcJrqtuXG2Efej6BkmMzA9IoFqwq/VSC+XhTuNitk07LDu9a2ACKVjwMRf6wkThja05qh5phhin20iI1K2Nk13lxx/F1dWIn9NBUfMgQnioAdIZHBzNKhai5JRHl4nz2TIUMD48xFDGLCLJTRgrWl6aokOap21HVxkK4LoRdIniwBoUWpmuqmQQZqUB4LQC24fJnmHecMIykk5QWHiV/GJjRQJcfeIotuVj5wruYMeEcaKLt/jLPNomoxUSilHgQ3FuLXfydFBRDCu2u89rE5KZJtrY/gf1NVt5qfEXhp+GkwQb6foa24qBKpS0Wp5FapxIF8jWODSOivWP1YQ7PsgS/sdl/KCggeAmWgLiEvPvKH+28/UIH6OZClWFuLZgdAifNo8Kr0m/GhZJh3v5ytr+9dZrfyPxDsUBAlKWD28UUxYaAyY2npvR5UUqhPe8nJezQireGrqp6TR5DFmfVxnXrEaFo1PNwbMLdHuxEQsTqQvJW6o/CUVS/dRiS5Hdw4G9rhDk4HY6HBwPAabHJy1oZkvx6EHE+u5RnTWzdjtwOGk
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secret-files
      namespace: monitoring
