---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-stack-credentials
  namespace: flux-system
spec:
  encryptedData:
    grafana_admin_password: AgB1KYcU4Arha/6wS6U8mvv3j5Eym3Z3FetDwzK/crTF1biMdaFkvJTkD4LPoc7+ESxIph4RqnPmDpYR6Oq9RvvpMOhnDUUdTb/k8UtH0GMAmepnmaBR3/K6qyFb25ZaZq8rBimOt4duxtsa5KLy3EyVV1KlY60ruVo5rvtZhDLSo0YG1gcu1uzhVLUKV40SaErMvUNR2PBDtZIZB0DBOOlswZNBzB804Dvsy7EvkUdUOgcLw+9gMdIEYiESUq8hVZgnA+dP/0FjsGqxgRE1cDZsR9CCOnY4pgfMUEILasN4mQuR6nM4sIGyLthGIO/zqH03cnQ5m87Fd6akAyle+Yg7GuiapVWwCw1gpvvQNLU1IyC6Vve1eDYgrbwEeqJqUjtQKR9uP5XdqpwWUGbfE8P6YnwBe81JNaLowHEHJ/ukWIB+ERiu7kh7/71QTQTucdkW0TzN19Yfzo9j5khPp4T1L+7rLgmEjJtR7j8PZi9LeIKVcqFwCdC5HNtyA7KSNmojxpM2uyF2ITc8gHZfHFF29GMIjPZ1xFITwUs8kwLPg700g8cOt4j+lto8ZK139h8vb9Eut2DbcPtDIEeugF/d+RvJR39cCz3wpaHlZQ4qvnEJimWzqtOrJpS9SE/xLV+FuSYBAIuJOTDzXVbVQAyFyuqjMX4Tx+GEPdwPehB7gi4CroeVJVnq/tz2QOby135SPdRsHt/izlzmFwoZEd3l
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-stack-credentials
      namespace: flux-system
