apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-telegram
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  route:
    groupBy: ['alertname', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 6h
    receiver: 'telegram'
  receivers:
  - name: 'telegram'
    telegramConfigs:
    - apiURL: https://api.telegram.org
      botTokenFile: /etc/alertmanager/secrets/alertmanager-secret-files/telegram-bot-token
      chatID: -880628191
      sendResolved: true
      parseMode: 'MarkdownV2'
