apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-telegram
  namespace: monitoring
  labels:
    alertmanagerConfig: telegram
spec:
  route:
    groupBy: ['alertname', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 6h
    receiver: 'telegram'
  receivers:
  - name: 'telegram'
    telegram_configs:
    - api_url: https://api.telegram.org
      bot_token_file: /etc/alertmanager/secrets/alertmanager-secret-files/telegram-bot-token
      chat_id: -880628191
      send_resolved: true
      parse_mode: 'MarkdownV2'
