---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - sealed-secrets.yaml
  - ./prometheus/prometheus-stack-credentials-sealed.yaml
  - ./prometheus/alertmanager-sealed.yaml
