---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus
      version: 26.0.1
  dependsOn:
    - name: sealed-secrets-controller
  interval: 30m
  releaseName: prometheus
  targetNamespace: monitoring
  values:
    kube-state-metrics:
      enabled: true
      resources:
        limits:
          cpu: 50m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 128Mi
    prometheus-node-exporter:
      enabled: true
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    prometheus-pushgateway:
      enabled: false
    server:
      ingress:
        enabled: true
        hosts:
        - prometheus.192.168.31.8.sslip.io
        ingressClassName: nginx
      persistentVolume:
        enabled: true
        size: 5Gi
        storageClass: "local-path"
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
      retention: 7d
      retentionSize: 5GB
      extraConfigmapMounts:
        - name: prometheus-alerts
          mountPath: /etc/alerts.d
          subPath: ""
          configMap: prometheus-alerts
          readOnly: true
    serverFiles:
      prometheus.yml:
        rule_files:
          - /etc/alerts.d/alerting_rules.yml
    alertmanager:
      replicaCount: 1
      persistence:
        enabled: true
        size: 50Mi
        storageClass: "local-path"
      resources:
        limits:
          cpu: 500m
          memory: 400Mi
        requests:
          cpu: 250m
          memory: 200Mi
      extraSecretMounts:
        - name: secret-files
          mountPath: /etc/secrets
          subPath: ""
          secretName: alertmanager-secret-files
          readOnly: true
      config:
        enabled: true
        global:
          resolve_timeout: 5m
        route:
          group_interval: 5m
          group_wait: 10s
          receiver: default-receiver
          repeat_interval: 3h
        templates:
          - '/etc/alertmanager/*.tmpl'
        receivers:
        - name: default-receiver
          telegram_configs:
          - api_url: https://api.telegram.org
            bot_token_file: /etc/secrets/telegram-bot-token
            chat_id: -880628191
            disable_notifications: false
            send_resolved: true
            parse_mode: 'HTML'
            message: '{{ template "telegram.message". }}' 
      templates:
        alertmanager.tmpl: |-
          {{ define "telegram.message" }}
          {{ range .Alerts }}
          {{ if eq .Status "firing"}}&#x1F525<b>{{ .Status | toUpper }}</b>&#x1F525{{ else }}&#x2705<b>{{ .Status | toUpper }}</b>&#x2705{{ end }}
          <b>{{ .Labels.alertname }}</b>
          {{- if .Labels.severity }}
          <b>Severity:</b> {{ .Labels.severity }}
          {{- end }}
          {{- if .Labels.cluster }}
          <b>Cluster:</b> {{ .Labels.cluster }}
          {{- end }}
          {{- if .Labels.service }}
          <b>Service:</b> {{ .Labels.service }}
          {{- end }}
          {{- if .Labels.instance}}
          <b>Instance:</b> {{ .Labels.instance }}
          {{- end }}
          <b>Description:</b> {{ .Annotations.description }}
          {{- end }}
