all:
  vars:
    ansible_user: 'pi'
    kubernetes_version: '1.32'
    kubernetes_pkg_version: '1.32.9-1.1'
    containerd_pkg_version: '1.7.27-1'
    haproxy_img_version: '2.8.15-alpine'
    sandbox_img_version: '3.10'
    loadbalancer_apiserver_port: 8443
    loadbalancer_apiserver_fqdn: 'cluster-endpoint'
  children:
    master:
      vars:
        cilium_version: '1.18.3'
        flux_version: '2.7.3'
        kubeseal_version: '0.33.1'
        gitlab_repository: orchestration
        gitlab_branch: main
        gitlab_path: 'clusters/rpi-cluster'
        gitlab_user: s045724
      hosts:
        192.168.31.20:
    worker:
      hosts:
        192.168.31.23:
    ingress:
      hosts:
        192.168.31.20:  
