router id 192.168.31.1;

log syslog all;

protocol device {}

protocol kernel {
    ipv4 {
        import all;
        export all;
    };

    persist;
    learn;
}

protocol direct {
    ipv4;
}

filter cilium_lb {
    if net.len = 32 then accept;
    reject;
}

protocol bgp cilium {

    local as 65000;

    neighbor range 192.168.31.0/24 external;

    dynamic name "cilium-";

    ipv4 {
        import filter cilium_lb;
        export none;
    };
}
