---
- name: Runbooks | Labeling all nodes.
  hosts: all
  gather_facts: true
  tasks:    
    - name: Set the fact to the current memory.
      ansible.builtin.set_fact:
        host_memory: "{{ (ansible_memtotal_mb/1024) | round | int }}"

    - name: Adding label for all node.
      local_action: ansible.builtin.command kubectl label node {{ ansible_hostname }} memory={{ host_memory }}

- name: Runbooks | Labeling master nodes.
  hosts: master
  vars:
    az: east-coast
  gather_facts: true
  tasks:
    - name: Adding label for master node.
      local_action: ansible.builtin.command kubectl label node {{ ansible_hostname }} topology.kubernetes.io/zone={{ az }}

- name: Runbooks | Labeling worker nodes.
  hosts: worker
  vars:
    az: west-coast
  gather_facts: true
  tasks:
    - name: Adding label for worker node.
      local_action: ansible.builtin.command kubectl label node {{ ansible_hostname }} topology.kubernetes.io/zone={{ az }}

    - name: Adding label for worker node.
      local_action: ansible.builtin.command kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/worker=
