---
- name: Runbooks | Labeling ingress nodes.
  hosts: ingress
  gather_facts: true
  tasks:
    - name: Adding label ingress.
      ansible.builtin.command: kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/ingress=true --overwrite
      delegate_to: localhost

- name: Runbooks | Labeling worker nodes.
  hosts: worker
  gather_facts: true
  tasks:
    - name: Adding label for worker node.
      ansible.builtin.command: kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/worker= --overwrite
      delegate_to: localhost

- name: Runbooks | Labeling etcd nodes.
  hosts: etcd
  gather_facts: true
  tasks:
    - name: Adding label for etcd node.
      ansible.builtin.command: kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/etcd= --overwrite
      delegate_to: localhost

- name: Runbooks | Labeling master nodes.
  hosts: master
  gather_facts: true
  tasks:
    - name: Adding label for etcd node.
      ansible.builtin.command: kubectl label node {{ ansible_hostname }} node-role.kubernetes.io/control-plane=
      delegate_to: localhost
      ignore_errors: true
