---
# ansible-playbook -i inventory/hosts.yaml runbooks/delete_node.yaml -l NODE_NAME -e delete_node=true -u pi --private-key=~/.ssh/ansible -CD
# ansible-playbook -i inventory/hosts.yml runbooks/delete_node.yaml -l NODE_NAME -e drain_node=true -e cleanup_node=true -u pi --private-key=~/.ssh/ansible -CD
- name: Runbooks | Delete nodes.
  hosts: all
  become: true
  tasks:
    - name: Drain node.
      ansible.builtin.command: kubectl drain {{ ansible_hostname }} --ignore-daemonsets --delete-emptydir-data --force
      delegate_to: localhost
      ignore_errors: true
      become: false
      when: drain_node | default(false) | bool

    - name: Cleanup node.
      when: cleanup_node | default(false) | bool
      block:
        - name: Kubeadm reset.
          ansible.builtin.command: kubeadm reset -f
          ignore_errors: true

        - name: Stop and disable the Services.
          ansible.builtin.systemd_service:
            name: "{{ item }}"
            state: stopped
            enabled: false
          loop:
            - kubelet
            - containerd
            - etcd
          ignore_errors: true

        - name: Unhold packages.
          ansible.builtin.dpkg_selections:
            name: "{{ item }}"
            selection: install
          loop:
            - kubeadm
            - kubelet
            - kubectl
            - containerd.io
          ignore_errors: true

        - name: Remove packages.
          ansible.builtin.apt:
            name:
              - kubeadm
              - kubelet
              - kubectl
              - containerd.io
              - kubernetes-cni
              - cri-tools
            state: absent
            purge: true

        - name: Remove folders.
          ansible.builtin.file:
            name: "{{ item }}"
            state: absent
          loop:
            - /etc/kubernetes
            - /etc/containerd
            - /etc/cni
            - /opt/cni
            - /opt/containerd
            - /opt/kubernetes
            - /var/lib/cni
            - /var/lib/kubelet
            - /var/lib/containerd
            - /var/lib/kubernetes
            - /var/log/containers
            - /var/log/pods
            - /var/lib/etcd
            - /etc/ssl/etcd

        - name: Remove user folders.
          ansible.builtin.file:
            name: "{{ item }}"
            state: absent
          loop:
            - "~/.kube"
          become: false
          become_user: "{{ ansible_user }}"

        - name: Delete node.
          ansible.builtin.command: kubectl delete node {{ ansible_hostname }}
          delegate_to: localhost
          become: false
          ignore_errors: true

        - name: Remove load balancer entry from /etc/hosts.
          ansible.builtin.lineinfile:
            path: /etc/hosts
            regexp: '.*{{ loadbalancer_apiserver_address }}.*'
            state: absent

        - name: Reboot node.
          ansible.builtin.reboot:
            reboot_timeout: 600
