---
# ansible-playbook -i inventory/hosts.yaml runbooks/delete_node.yaml -l NODE_NAME -e delete_node=true -u pi --private-key=~/.ssh/ansible -CD
- name: Runbooks | Delete nodes.
  hosts: all
  become: true
  tasks:
    - name: Delete node.
      when: delete_node | default(false) | bool
      block:
        - name: Drain node.
          local_action: ansible.builtin.command kubectl drain {{ ansible_hostname }} --ignore-daemonsets --delete-emptydir-data
          ignore_errors: true
          become: false

        - name: Delete node.
          local_action: ansible.builtin.command kubectl delete node {{ ansible_hostname }}
          become: false

        - name: Stop and disable the Kubelet service.
          ansible.builtin.systemd_service:
            name: kubelet
            state: stopped
            enabled: false

        - name: Kubeadm reset.
          ansible.builtin.command: kubeadm reset -f
