---
- name: Runbooks | Make master nodes possible to schedule.
  hosts: master
  tasks:
    - name: Remove NoSchedule taint.
      local_action: ansible.builtin.command kubectl taint node {{ ansible_hostname }} node-role.kubernetes.io/control-plane:NoSchedule-
