---
# ansible-playbook -i inventory/hosts.yaml runbooks/upgrade_cluster_config.yaml -e upload_config=true
# ansible-playbook -i inventory/hosts.yaml runbooks/upgrade_cluster_config.yaml -l master -e cp_upgrade=true -e kubelet_upgrade=true
# ansible-playbook -i inventory/hosts.yaml runbooks/upgrade_cluster_config.yaml -l worker -e kubelet_upgrade=true
- name: Runbooks | Upgrade cluster config.
  hosts: master[0]
  gather_facts: false
  become: true
  vars:
    cluster_config: |
      ---
      apiVersion: kubeadm.k8s.io/v1beta4
      kind: ClusterConfiguration
      controlPlaneEndpoint: {{ loadbalancer_apiserver_fqdn }}:{{ loadbalancer_apiserver_port }}
      controllerManager:
        extraArgs:
        - name: feature-gates
          value: InPlacePodVerticalScaling=true
      apiServer:
        extraArgs:
        - name: feature-gates
          value: InPlacePodVerticalScaling=true
      kubernetesVersion: v{{ kubernetes_pkg_version.split('-')[0] }}
      proxy:
        disabled: true
      scheduler:
        extraArgs:
        - name: feature-gates
          value: InPlacePodVerticalScaling=true
      ---
      apiVersion: kubelet.config.k8s.io/v1beta1
      kind: KubeletConfiguration
      featureGates:
        InPlacePodVerticalScaling: true
  tasks:
    - name: Upload config to cluster.
      when: upload_config | default(false) | bool
      block:
        - name: Copy config from variable.
          ansible.builtin.copy:
            content: "{{ cluster_config }}"
            dest: /home/{{ ansible_user }}/cluster-config.yaml
            mode: '0644'

        - name: Get file status.
          ansible.builtin.stat:
            path: /home/{{ ansible_user }}/cluster-config.yaml
          register: file_check_result

        - name: Load config to cluster.
          ansible.builtin.shell: "kubeadm init phase upload-config all --config cluster-config.yaml > config_upgrade.log 2>&1"
          args:
            chdir: /home/{{ ansible_user }}
          when: file_check_result.stat.exists

- name:  Runbooks | Upgrade nodes.
  hosts: all
  serial: 1
  become: true
  tasks:
    - name: Apply new changes to control-plane.
      ansible.builtin.shell: "kubeadm upgrade node phase control-plane > control-plane_upgrade.log 2>&1"
      args:
        chdir: /home/{{ ansible_user }}
      when: cp_upgrade | default(false) | bool

    - name: Apply new changes to kubelet.
      ansible.builtin.shell: "kubeadm upgrade node phase kubelet-config > kubelet_upgrade.log 2>&1"
      args:
        chdir: /home/{{ ansible_user }}
      when: kubelet_upgrade | default(false) | bool

    - name: Drain node.
      local_action: ansible.builtin.command kubectl drain {{ ansible_hostname }} --ignore-daemonsets --delete-emptydir-data
      ignore_errors: true
      become: false
      when: kubelet_upgrade | default(false) | bool

    - name: Pause 180 second for Pod eviсtion.
      ansible.builtin.pause:
        seconds: 180
      when: kubelet_upgrade | default(false) | bool

    - name: Restart service kubelet.
      ansible.builtin.systemd_service:
        state: restarted
        daemon_reload: true
        name: kubelet
      when: kubelet_upgrade | default(false) | bool

    - name: Uncordon node.
      local_action: ansible.builtin.command kubectl uncordon {{ ansible_hostname }}
      become: false
      when: kubelet_upgrade | default(false) | bool
