---
- name: Runbook to upgrade etcd.
  hosts: etcd
  become: true
  serial: 1
  tasks:
    - name: Check etcd binary exist.
      ansible.builtin.stat:
        path: "{{ bin_dir }}/etcd"
      register: etcd_check

    - name: Get etcd version.
      ansible.builtin.command: "{{ bin_dir }}/etcd --version"
      register: etcd_version_raw
      changed_when: false

    - name: Extract etcd version.
      ansible.builtin.set_fact:
        etcd_current_version: "{{ etcd_version_raw.stdout | regex_search('etcd Version: ([0-9.]+)', '\\1') | first }}"

    - name: Show current version.
      ansible.builtin.debug:
        var: etcd_current_version

    - name: Upgrade etcd cluster.
      when: etcd_current_version is version(etcd_version, '<', version_type='semver')
      throttle: 1
      block:
        - name: Download new version etcd.
          ansible.builtin.unarchive:
            src: https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}.tar.gz
            dest: /tmp
            remote_src: true
            mode: '0755'

        - name: Stop etcd.
          ansible.builtin.systemd_service:
            name: etcd
            state: stopped

        - name: Copy etcd binaries to /usr/local/bin.
          ansible.builtin.copy:
            src: "{{ item }}"
            dest: "{{ bin_dir }}"
            remote_src: true
            mode: '0755'
          loop:
            - "/tmp/etcd-v{{ etcd_version }}-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/etcd"
            - "/tmp/etcd-v{{ etcd_version }}-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/etcdctl"
            - "/tmp/etcd-v{{ etcd_version }}-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/etcdutl"

        - name: Start etcd and enabled at boot.
          ansible.builtin.systemd_service:
            name: etcd
            state: started
            enabled: true

        - name: Verify etcd cluster health.
          ansible.builtin.pause:
