---
# ansible-playbook -i inventory/hosts.yaml runbooks/upgrade_cluster.yaml -u pi --private-key=~/.ssh/ansible -e upgrade_cri=true -CD
- name: Runbooks | Upgrade Kubernetes on first master node.
  hosts: master[0]
  become: true
  tasks:
    - name: Get package facts.
      ansible.builtin.package_facts:
        manager: apt

    - name: Set the fact to the current kubeadm version.
      ansible.builtin.set_fact:
        current_version: "{{ ansible_facts.packages['kubeadm'][0].version.split('-')[0] }}"
        desired_version: "{{ kubernetes_pkg_version.split('-')[0] }}"

    - name: Upgrade cluster.
      when: current_version is version(desired_version, '<', version_type='semver')
      block:
    # Add repos
        - name: Add repos.
          ansible.builtin.include_tasks: ../playbooks/tasks/add_repos.yaml

        - name: Drain node.
          ansible.builtin.command: kubectl drain {{ ansible_hostname }} --ignore-daemonsets --delete-emptydir-data
          delegate_to: localhost
          ignore_errors: true
          become: false

        - name: Allow Kubeadm to be upgraded.
          ansible.builtin.dpkg_selections:
            name: "{{ item }}"
            selection: install
          loop:
            - kubeadm

        - name: Install Kubeadm.
          ansible.builtin.apt:
            name:
              - kubeadm={{ kubernetes_pkg_version }}
            state: present

        - name: Fetching available versions to upgrade.
          ansible.builtin.shell: "kubeadm upgrade plan > cluster_upgrade_v{{ desired_version }}.log 2>&1"
          args:
            chdir: /home/{{ ansible_user }}
            creates: cluster_upgrade_v{{ desired_version }}.log

        - name: Change the cluster version.
          ansible.builtin.shell: "kubeadm upgrade apply v{{ desired_version }} --yes --skip-phases={{ kubeadm_init_phases_skip | join(',') }} > node_upgrade_v{{ desired_version }}.log 2>&1"
          args:
            chdir: /home/{{ ansible_user }}
            creates: node_upgrade_v{{ desired_version }}.log

        - name: Allow Kubectl, Kubelet to be upgraded.
          ansible.builtin.dpkg_selections:
            name: "{{ item }}"
            selection: install
          loop:
            - kubelet
            - kubectl

        - name: Install Kubectl, Kubelet.
          ansible.builtin.apt:
            name:
              - kubelet={{ kubernetes_pkg_version }}
              - kubectl={{ kubernetes_pkg_version }}
            state: present

        - name: Allow ContainerD to be upgraded.
          ansible.builtin.dpkg_selections:
            name: "{{ item }}"
            selection: install
          loop:
            - containerd.io
          when: upgrade_cri | default(false) | bool

        - name: Install ContainerD.
          ansible.builtin.apt:
            name:
              - containerd.io={{ containerd_pkg_version }}
            state: present
          when: upgrade_cri | default(false) | bool

        - name: Prevent Kubeadm, Kubectl, Kubelet from being upgraded.
          ansible.builtin.dpkg_selections:
            name: "{{ item }}"
            selection: hold
          loop:
            - kubeadm
            - kubelet
            - kubectl

        - name: Prevent ContainerD from being upgraded.
          ansible.builtin.dpkg_selections:
            name: "{{ item }}"
            selection: hold
          loop:
            - containerd.io
          when: upgrade_cri | default(false) | bool

        - name: Start service containerd, if not started.
          ansible.builtin.systemd_service:
            state: restarted
            name: containerd
          when: upgrade_cri | default(false) | bool

        - name: Restart service Kubectl, also issue daemon-reload to pick up config changes.
          ansible.builtin.systemd_service:
            state: restarted
            daemon_reload: true
            name: kubelet

        - name: Pause 60 second for start static pods.
          ansible.builtin.pause:
            seconds: 60

        - name: Uncordon node.
          ansible.builtin.command: kubectl uncordon {{ ansible_hostname }}
          delegate_to: localhost
          become: false
