---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred-dockerhub
  namespace: apps
spec:
  encryptedData:
    .dockerconfigjson: AgCcuJZ4YjClRw+hSXAtIBb0pyeCJ3fCaCcFqzyt0tSnY0ZgA0/k0Divk2GFAkDYVHp7kYfLgXYPIJrFA7yU5UKK1dVeiUjKXCM72wQctfCOW/LcLKHpn2ASi4JbsADrqFeIWJRVHnEARlg+6+EyesrpA4x4+RO8A88wbUby7LOR1C7iwboyw3C2lmUdFP4SgosquNlxHg2oW8EYg/anNSEWTnT/oIuIhZtkCxPd73KBlGMouSdTB0XaODYffomRvytxH+UKZbS4IH7DNbdTLIFCVi7xBcBIx4UhqQQCao8x0dHOpNF6Yr0DdB6HZaHIqChY+jZjzeWMfF4cbd+aCdKvMmj1iuqchzLgFxnbbtPs9w8mI1svYjoNYbs3fFAP7QMtlzyFl9uI/wX2SjqT5vq8j9SJ5DCER9J0wCzaOQrMnfcMaHDdP98LkwYrtL6STbSvvO7s/dyL5I5kEZL9o9Dfe6KRo26LoRTBuRX4psWoF0xi0GVY2DHS+6SrLEm3AiHrmX7Of8MUlVbkD40nsMwZFZu4mItyZ7Hy7T4VBSMqmjePDrBLT7+wpN6yx1HNrugy840NhjeKGapMNbu6j9eLf/kUfPLbkeq0VzrM1qqgwRVxhYn29n8g25TFSega81C7MuS6kl23Trl/ZNvd1wup8f5qD5z5KCnpd0vK4sSYGuVYsd1St6bs72gqVbGwlMFbzgQZYNedgyvlmqFTXJjXZcAd5oxDJhipwrgT4NwDPSbSwyjcWKqkt6fmsTtiGuikGMhzgb520MpEXX67moM6BIsm9JBkyS1ivwF/9Wd5cAqG4rN4aWNj9XomFx/z+ZzPkGgtMr9hPhyeotJm/zHmOLgVIzAonuZtcYwvHfzdPM1s+vlkvGXRlkX72cedxiRlj0k/Wf0LUGTz/PcK7PqlyQDJi61h581i8o6xWAzumflIgRSy1X+pnv6Cc06wAFO8RCc0TQjnaWs7V+zVfgudP8az3fc4qnBnFamMF4sabRWDxeQGla9Ee9OcWS2ty08uCA==
  template:
    metadata:
      name: regcred-dockerhub
      namespace: apps
    type: kubernetes.io/dockerconfigjson
