---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred-dockerhub
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgATR+hNVRp+krVD+B/ticTgPBPYNENUUArFj7DrfCc9GVqNh7Y7KUPuycxYF934bk9jSx39mIuhILhDJ1M+eeUwXSjB3/4iXyHQb3KsP4b6nmf2E/x7dWtEOKA2Gb4mkFe4GBw2bA+SbRSSIHSFVpVOpsontoIDw/HbFD3dOkVENIjkk6tBJfD2fRlmhJHowpSudcvD4mm+PWGF6w2WB/Vnajf8Rw6QB6zRh62I8lwnEZLKpO5TiCyuepxxgW3+ca/SXLEJykw3ZhGgi0xVP/bRqR2Ga9orvakRgbyqM5sG2wIbltQ7ShQ/AGXKm6kfczOkIXkepr0hpCUqmhHSTzdxhndkw4hWu6bHMdY3jt7guiOJU9L22jBifMAQP32cUkO5D7Pjb6hj8sg9LBRtAuXY0JEsa5jOePPmeF/KsjWGsOZyxjc6rnA9sbRvAl9HASwocAwvU2/1RVhkcZz0DQrpoZiPZaU8Rp1H2o5tFK9vTIIN4Bx3oC+xthrz11RlgaKQKqCn/U84T00lOpqRxCvJUiYzDMxwBmzNndhOULg/MLEOrskBCCXcsuw71lo7DOxBqakChNa2zuOGrnde83YiqPdSvUIWOVGyG+C47tqyhQx48VHKpElWbYFHSnGm8emHTWbpmtcq4KjOEOdvN3uy6WdLA//NB7eB+hbZzvYW2qM36ccbVF/13iT+hHPIKd+495KA3Be5gFq9sYd9ptViUNKanenQnLzf7qiYrAtYcF1696fgbRy+a2y0tKJ4SXXH/KmHYx+h5Ci4upAEU1UsQD5735+ljqizo/EA8pSmipVfvOIMzsqIWJBPJWphxnjBQqylBhnMUftfVeh40LlvA+WGdOdDfjCGhDFQu/TFbW8OBrXYuNVU5Be8oaazhOM0jSyIMhIwNNqodJ9d4XZWcyneTjGoPhXjGKVbCGhGija+yHEsfc2GL5pg/QY7pkYllgR6GFwGbi8pE0V8ewJXqcFRz1bw8tYnmPj4szeVRN2PlgCg+LRPyy/7xt5qVLISVQ==
  template:
    metadata:
      name: regcred-dockerhub
      namespace: default
    labels:
      sync: "true"
    type: kubernetes.io/dockerconfigjson
