---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno-post-deploy
  namespace: flux-system
spec:
  dependsOn:
    - name: base-post-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./infra/post-deploy/kyverno-policies"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
