---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-vpa-deployment
  annotations:
    policies.kyverno.io/description: >-
      Creates a VerticalPodAutoscaler resource with MODE = Off for a Deployment
      in the namespace of the original resource. As the MODE is Off, this
      simply provides recommendations for MEM and CPU.
spec:
  validationFailureAction: Enforce
  rules:
  - name: generate-vpa
    match:
      any:
      - resources:
          kinds:
          - Deployment
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - kube-node-lease
          - kube-public
          - ingress-nginx
          - local-path-storage
    generate:
      kind: VerticalPodAutoscaler
      apiVersion: autoscaling.k8s.io/v1
      name: "{{request.object.metadata.name}}"
      namespace: "{{request.object.metadata.namespace}}"
      synchronize: true
      generateExisting: true
      data:
        metadata:
          labels:
            created-by: kyverno
        spec:
          targetRef:
            apiVersion: "apps/v1"
            kind:       Deployment
            name:       "{{request.object.metadata.name}}"
          updatePolicy:
            updateMode: "Off"
          resourcePolicy:
            containerPolicies:
              - containerName: '*'
                controlledResources: ["cpu", "memory"]
