---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubecert-expiration
  namespace: monitoring
spec:
  groups:
    - name: kubernetes-certificates
      rules:
        - alert: KubernetesCertificateExpiresIn90Days
          expr: |
            kubeadm_cert_expiry_seconds - time() < 90 * 24 * 60 * 60
            and kubeadm_cert_expiry_seconds - time() >= 0
          for: 1h
          labels:
            severity: warning
          annotations:
            summary: "Kubernetes certificate {{ $labels.name }} expires in less than 90 days"
            description: >-
              Certificate {{ $labels.name }} ({{ $labels.path }})
              in group {{ $labels.group }} expires in less than 90 days.

        - alert: KubernetesCertificateExpired
          expr: |
            kubeadm_cert_expiry_seconds - time() < 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Kubernetes certificate {{ $labels.name }} has expired"
            description: >-
              Certificate {{ $labels.name }} ({{ $labels.path }})
              in group {{ $labels.group }} has expired.
