---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-gateway-cert
  namespace: monitoring
spec:
  secretName: monitoring-gateway-tls
  dnsNames:
    - "*.192.168.100.1.sslip.io"
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
