---
- name: Prepare nodes.
  hosts: all
  become: true
  tasks:
    - name: Create kubernetes directories.
      when: "'master' in group_names"
      block:
        - name: Create kubernetes directory.
          ansible.builtin.file:
            path: "{{ kube_config_dir }}"
            state: directory
            mode: '0751'
            owner: root

        - name: Make least directory.
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: '0700'
            owner: root
          loop:
            - "{{ kube_cert_dir }}"
            - "{{ kube_cert_dir }}/etcd"
            - "{{ kube_manifest_dir }}"

    - name: Create user and etcd directories.
      when:
        - groups['master'] | length >= 3
        - groups['etcd'] | length in [3, 5]
        - "'etcd' in group_names"
      block:
        - name: Ensure group etcd exists.
          ansible.builtin.group:
            name: "{{ etcd_owner }}"
            system: true
            state: present

        - name: Create etcd user.
          ansible.builtin.user:
            name: "{{ etcd_owner }}"
            group: "{{ etcd_owner }}"
            shell: /usr/sbin/nologin
            create_home: false
            system: true
            state: present

        - name: Create etcd directories.
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            owner: "{{ etcd_owner }}"
            group: "{{ etcd_owner }}"
            mode: '0700'
          loop:
            - "{{ etcd_config_dir }}"
            - "{{ etcd_cert_dir }}"
            - "{{ etcd_data_dir }}"

    - name: Include etcd cert tasks.
      ansible.builtin.include_tasks: tasks/copy_etcd_certs.yaml
      when:
        - groups['master'] | length >= 3
        - groups['etcd'] | length in [3, 5]

    - name: Include etcd tasks.
      ansible.builtin.include_tasks: tasks/install_etcd.yaml
      when:
        - groups['master'] | length >= 3
        - groups['etcd'] | length in [3, 5]
        - "'etcd' in group_names"

    - name: Check cluster initialized files.
      ansible.builtin.stat:
        path: "{{ item }}"
      loop:
        - /home/{{ ansible_user }}/cluster_initialized.log
        - /home/{{ ansible_user }}/node_joined.log
      register: cluster_initialized_files

    - name: Add external cluster lb bootstrap ip.
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ groups['master'][0] }}        {{ loadbalancer_apiserver_address }}"
      when: cluster_initialized_files.results | selectattr('stat.exists') | list | length == 0

- name: Initialize Kubernetes cluster.
  hosts: master
  become: true
  gather_facts: false
  tasks:
    - name: Write kubeadm config.
      ansible.builtin.template:
        src: kubeadm-config.yaml.j2
        dest: "{{ kube_config_dir }}/kubeadm-config.yaml"
        mode: '0600'
        owner: root
        backup: true
        validate: "kubeadm config validate --config %s"
      when: inventory_hostname == groups['master'][0]

    - name: Create certs on first control-plane node.
      when:
        - groups['master'] | length >= 3
        - groups['etcd'] | length in [3, 5]
        - inventory_hostname == groups['master'][0]
      block:
        - name: Generate all Kubernetes certificates.
          ansible.builtin.command: kubeadm init phase certs all --config={{ kube_config_dir }}/kubeadm-config.yaml
          args:
            chdir: "{{ kube_config_dir }}"
            creates: "{{ kube_cert_dir }}/ca.key"

        - name: Check generated certificates.
          ansible.builtin.command: kubeadm certs check-expiration
          changed_when: false
          register: cert_check

        - name: Display certificate expiration.
          ansible.builtin.debug:
            var: cert_check.stdout_lines

        - name: Fetch kubernetes certificates from first node.
          ansible.builtin.fetch:
            src: "{{ kube_cert_dir }}/{{ item }}"
            dest: "/tmp/kubernetes-certs/"
            flat: true
          loop:
            - "ca.crt"
            - "ca.key"
            - "front-proxy-ca.crt"
            - "front-proxy-ca.key"
            - "sa.key"
            - "sa.pub"

    - name: Distribute kubernetes certificates to other nodes.
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ kube_cert_dir }}/{{ item | basename }}"
        owner: root
        group: root
        mode: "{{ '0600' if item is match('.*\\.(key|pub)$') else '0644' }}"
      loop: "{{ lookup('ansible.builtin.fileglob', '/tmp/kubernetes-certs/*', wantlist=True) }}"
      when:
        - groups['master'] | length >= 3
        - groups['etcd'] | length in [3, 5]
        - inventory_hostname != groups['master'][0]

    # HA
    - name: Initialize the HA-cluster.
      # ansible.builtin.shell: kubeadm init --config kubeadm-config.yaml --upload-certs --skip-phases=addon/kube-proxy > cluster_initialized.log 2>&1
      ansible.builtin.shell: kubeadm init --config kubeadm-config.yaml --skip-phases={{ kubeadm_init_phases_skip | join(',') }} > /home/{{ ansible_user }}/cluster_initialized.log 2>&1
      args:
        chdir: "{{ kube_config_dir }}"
        creates: /home/{{ ansible_user }}/cluster_initialized.log
      when:
        - groups['master'] | length >= 3
        - groups['etcd'] | length in [3, 5]
        - inventory_hostname == groups['master'][0]

    # non-HA
    - name: Initialize the cluster.
      ansible.builtin.shell: kubeadm init --config kubeadm-config.yaml --skip-phases={{ kubeadm_init_phases_skip | join(',') }} > /home/{{ ansible_user }}/cluster_initialized.log 2>&1
      args:
        chdir: "{{ kube_config_dir }}"
        creates: /home/{{ ansible_user }}/cluster_initialized.log
      when:
       - groups['master'] | length == 1
       - inventory_hostname == groups['master'][0]

    - name: Include kubeconfig copy tasks.
      ansible.builtin.include_tasks: tasks/copy_kubeconfig.yaml
      when: inventory_hostname == groups['master'][0]
