---
- name: Install dependencies on all hosts.
  hosts: all
  become: true
  tasks:
    - name: Add proxy.
      ansible.builtin.include_tasks: tasks/add_proxy.yaml

    - name: Add repos.
      ansible.builtin.include_tasks: tasks/add_repos.yaml

    # Upgrade the OS

    - name: Upgrade OS.
      when: upgrade_os | default(false) | bool
      block:
        - name: Upgrade the OS (apt-get dist-upgrade).
          ansible.builtin.apt:
            upgrade: dist

        - name: Check if a reboot is needed.
          ansible.builtin.stat:
            path: "{{ item }}"
          loop:
            - /var/run/reboot-required
            - /var/run/reboot-required.pkgs
          register: reboot_required_files

        - name: Reboot, if needed.
          ansible.builtin.reboot:
          when: reboot_required_files.results | selectattr('stat.exists') | list | length > 0

        - name: Remove dependencies that are no longer required.
          ansible.builtin.apt:
            autoremove: true

    # Disable SWAP

    - name: Disable SWAP.
      ansible.builtin.command: swapoff -a
      changed_when: false

    - name: Disable SWAP in fstab.
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    # Install modules and add kernel settings

    - name: Load kernel modules.
      community.general.modprobe:
        name: "{{ item }}"
        state: present
        persistent: present
      loop:
        - br_netfilter
        - overlay

    - name: Create file /etc/sysctl.d/kubernetes.conf.
      ansible.posix.sysctl:
        name: "{{ item }}"
        value: '1'
        sysctl_file: /etc/sysctl.d/kubernetes.conf
        reload: true
      loop:
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.ip_forward

    - name: Unhold packages.
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: install
      loop:
        - kubeadm
        - kubelet
        - kubectl
        - containerd.io
        - haproxy
        - cri-tools
      ignore_errors: true

    # Install HAProxy

    - name: Install HAProxy.
      when:
        - groups['master'] | length >= 3
      block:
        - name: Install HAProxy.
          ansible.builtin.apt:
            name:
              - haproxy={{ haproxy_pkg_version }}
            state: present

        - name: Write HAProxy configuration.
          ansible.builtin.template:
            src: haproxy.cfg.j2
            dest: "{{ haproxy_config_dir }}/haproxy.cfg"
            owner: root
            mode: '0644'
            backup: true
          notify: Restart haproxy.

        - name: Enable and start the HAProxy service.
          ansible.builtin.systemd_service:
            name: haproxy
            state: started
            enabled: true

    # Install Containerd

    - name: Install Containerd.
      ansible.builtin.apt:
        name: containerd.io={{ containerd_pkg_version }}
        state: present
      notify: Generate Containerd config.

    - name: Force all notified handlers to run at this point.
      ansible.builtin.meta: flush_handlers

    - name: Configuring Systemd cgroup driver for Containerd.
      ansible.builtin.lineinfile:
        path: "{{ containerd_config_dir }}/config.toml"
        regexp: "            SystemdCgroup = false"
        line: "            SystemdCgroup = true"
        backup: true
      notify: Restart containerd.

    - name: Configuring Pause image version.
      ansible.builtin.lineinfile:
        path: "{{ containerd_config_dir }}/config.toml"
        regexp: "^      sandbox"
        line: "      sandbox = '{{ sandbox_image }}'"
        backup: true
      notify: Restart containerd.

    - name: Write containerd systemd init file.
      ansible.builtin.include_tasks: tasks/write_containerd_init.yaml

    - name: Enable and start the Containerd service.
      ansible.builtin.systemd_service:
        name: containerd
        state: started
        enabled: true

    # Install kubeadm, kubelet, Kubectl

    - name: Install Kubeadm, Kubelet packages.
      ansible.builtin.apt:
        name:
          - kubelet={{ kubernetes_pkg_version }}
          - kubeadm={{ kubernetes_pkg_version }}
          - kubectl={{ kubernetes_pkg_version }}
          - cri-tools={{ cri_tools_pkg_version }}
        state: present

    - name: Write kubelet systemd init file.
      ansible.builtin.include_tasks: tasks/write_kubelet_init.yaml

    - name: Set the crictl endpoint in the configuration file.
      ansible.builtin.copy:
        dest: /etc/crictl.yaml
        content: |
          runtime-endpoint: unix:///var/run/containerd/containerd.sock
          image-endpoint: unix:///var/run/containerd/containerd.sock
          timeout: 10
          debug: true
        owner: root
        group: root
        mode: '0644'

    - name: Hold Kubeadm, Kubelet packages.
      ansible.builtin.dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl
        - containerd.io
        - haproxy
        - cri-tools

    # Install Cilium CLI

    - name: Download Cilium CLI.
      ansible.builtin.unarchive:
        src: https://github.com/cilium/cilium-cli/releases/download/v{{ cilium_cli_version }}/cilium-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}.tar.gz
        dest: /tmp
        remote_src: true
        mode: '0755'

    - name: Copy Cilium binary to /usr/local/bin.
      ansible.builtin.copy:
        src: /tmp/cilium
        dest: "{{ bin_dir }}/cilium"
        remote_src: true
        mode: '0755'

    # Linux

    - name: Add linux tasks.
      ansible.builtin.include_tasks: tasks/common_linux.yaml

  handlers:
    - name: Generate Containerd config.
      ansible.builtin.shell: /usr/bin/containerd config default > {{ containerd_config_dir }}/config.toml
      changed_when: false

    - name: Reload systemd.
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Restart containerd.
      ansible.builtin.systemd_service:
        name: containerd
        state: restarted

    - name: Restart haproxy.
      ansible.builtin.systemd_service:
        name: haproxy
        state: restarted

    - name: Restart journald.
      ansible.builtin.systemd_service:
        name: systemd-journald.service
        state: restarted

    - name: Restart atop.
      ansible.builtin.service:
        name: atop
        state: restarted
