---
- name: Playbook to install CNI.
  hosts: master[0]
  become: true
  tasks:
    - name: Add repos.
      ansible.builtin.include_tasks: tasks/add_repos.yaml

    # Install Helm

    - name: Install Helm.
      ansible.builtin.apt:
        name: helm={{ helm_pkg_version }}
        state: present

    # Install CNI Cilium

    - name: Add Cilium chart repo.
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: "https://helm.cilium.io/"

    - name: Deploy CNI Cilium chart.
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        chart_version: "{{ cilium_version }}"
        release_namespace: kube-system
        update_repo_cache: true
        kubeconfig: /etc/kubernetes/admin.conf
        values:
          kubeProxyReplacement: true
          k8sServiceHost: "{{ loadbalancer_apiserver_address if (groups['master'] | length >= 3) else groups['master'][0] }}"
          k8sServicePort: "{{ loadbalancer_apiserver_port if (groups['master'] | length >= 3) else '6443' }}"
          bgpControlPlane:
            enabled: true
          rollOutCiliumPods: false
#          extraConfig:
#            ipv4-service-range: "{{ kube_service_subnets }}"
          ipam:
            operator:
              clusterPoolIPv4PodCIDRList: ["{{ kube_pods_subnet }}"]
              clusterPoolIPv4MaskSize: 24
          ipv4:
            enabled: true
          operator:
            rollOutPods: false
          ipv4NativeRoutingCIDR: "{{ kube_pods_subnet }}"
          autoDirectNodeRoutes: true
          routingMode: native
          bpfClockProbe: true
          bpf:
            datapathMode: netkit
            masquerade: true
            mapDynamicSizeRatio: 0.08
            distributedLRU:
              enabled: true
          envoy:
            enabled: false
          hubble:
            enabled: false
#          l2announcements:
#            enabled: true
#          k8sClientRateLimit:
#            burst: 100
#            qps: 50

- name: Install the Cilium CLI.
  hosts: master
  become: true
  tasks:
    - name: Download Cilium CLI.
      ansible.builtin.unarchive:
        src: https://github.com/cilium/cilium-cli/releases/download/v{{ cilium_cli_version }}/cilium-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}.tar.gz
        dest: /tmp
        remote_src: true
        mode: '0755'

    - name: Copy Cilium binary to /usr/local/bin.
      ansible.builtin.copy:
        src: /tmp/cilium
        dest: "{{ bin_dir }}/cilium"
        remote_src: true
        mode: '0755'
