---
- name: Initialize Kubernetes cluster.
  hosts: master[0]
  become: true
  tasks:
    # CNI Cilium HA
    - name: Initialize the HA-cluster.
      ansible.builtin.shell: kubeadm init --control-plane-endpoint {{ loadbalancer_apiserver_fqdn }}:{{ loadbalancer_apiserver_port }} --upload-certs --skip-phases=addon/kube-proxy > cluster_initialized.log 2>&1
      args:
        chdir: /home/{{ ansible_user }}
        creates: cluster_initialized.log
      when: "groups['master'] | length > 1"

    # CNI Cilium non-HA
    - name: Initialize the cluster.
      ansible.builtin.shell: kubeadm init --skip-phases=addon/kube-proxy > cluster_initialized.log 2>&1
      args:
        chdir: /home/{{ ansible_user }}
        creates: cluster_initialized.log
      when: "groups['master'] | length == 1"

    - name: Include kubeconfig copy tasks.
      ansible.builtin.include_tasks: tasks_copy_kubeconfig.yaml

    - name: Add Cilium chart repo.
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: "https://helm.cilium.io/"

    - name: Deploy CNI Cilium chart.
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        chart_version: "{{ cilium_version }}"
        release_namespace: kube-system
        update_repo_cache: true
        kubeconfig: /etc/kubernetes/admin.conf
        values:
          kubeProxyReplacement: true
          k8sServiceHost: "{{ loadbalancer_apiserver_fqdn if (groups['master'] | length > 1) else groups['master'][0] }}"
          k8sServicePort: "{{ loadbalancer_apiserver_port if (groups['master'] | length > 1) else '6443' }}"
          ipv4NativeRoutingCIDR: 10.0.0.0/8
          autoDirectNodeRoutes: true
          routingMode: native
          ipv4:
            enabled: true
          bpf:
            datapathMode: netkit
            masquerade: true
          rollOutCiliumPods: true
          operator:
            rollOutPods: true
          envoy:
            enabled: false
