---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluent
  namespace: flux-system
spec:
  interval: 24h
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: flux-system
spec:
  chart:
    spec:
      chart: fluent-bit
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluent
      version: 0.55.0
  dependsOn:
    - name: loki
  interval: 30m
  releaseName: fluent-bit
  targetNamespace: logs
  values:
    tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    securityContext:
       capabilities:
         add:
         - CAP_SYSLOG
    config:
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
            Buffer_Size 64KB
      inputs: |
        [INPUT]
            Name kmsg
            Tag kernel.*

        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            Exclude_Path /var/log/containers/fluent-bit-*.log
            multiline.parser docker, cri
            Tag kube.*
            Mem_Buf_Limit 5MB
            Skip_Long_Lines On

        [INPUT]
            Name systemd
            Tag host.*
            Systemd_Filter _SYSTEMD_UNIT=kubelet.service
            Systemd_Filter _SYSTEMD_UNIT=containerd.service
            Read_From_Tail On
      outputs: |
        [OUTPUT]
            Name loki
            Match kube.*
            host loki-gateway
            port 80
            labels job=fluentbit
            label_keys $sub['stream']
            auto_kubernetes_labels true

        [OUTPUT]
            Name loki
            Match host.*
            host loki-gateway
            port 80
            labels job=fluentbit
            label_keys $sub['stream']

        [OUTPUT]
            Name loki
            Match kernel.*
            host loki-gateway
            port 80
            labels job=fluentbit
            label_keys $sub['stream']
