---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: deliveryhero
  namespace: flux-system
spec:
  interval: 24h
  url: oci://ghcr.io/deliveryhero/helm-charts
  type: "oci"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-event-logger
  namespace: flux-system
spec:
  chart:
    spec:
      chart: k8s-event-logger
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: deliveryhero
      version: 1.1.10
  interval: 30m
  releaseName: k8s-event-logger
  targetNamespace: logs
  values:
    containerName: eventrouter
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
