---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 81.6.9
  dependsOn:
    - name: local-path-provisioner
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  timeout: 10m0s
  interval: 30m
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  values:
    grafana:
      enabled: true
      defaultDashboardsTimezone: "Asia/Yekaterinburg"
      defaultDashboardsEnabled: true
      ingress:
        enabled: true
        hosts:
          - grafana.192.168.31.8.sslip.io
        ingressClassName: nginx
      resources:
        requests:
          cpu: 250m
          memory: 400Mi
        limits:
          cpu: 500m
          memory: 500Mi
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
          label: grafana_dashboard
          labelValue: "1"
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-gateway.logs.svc.cluster.local
          editable: true
          basicAuth: false
          access: proxy
    defaultRules:
      disabled:
        InfoInhibitor: true
        Watchdog: true
    alertmanager:
      enabled: true
      config:
        global:
          resolve_timeout: 5m
        route:
          receiver: telegram-alert
          group_by: ['alertname', 'cluster', 'service']
          group_interval: 5m
          repeat_interval: 12h
          group_wait: 30s
          routes:
            - match_re:
                severity: "warning|critical"
              receiver: telegram-alert
        receivers:
          - name: telegram-alert
            telegram_configs:
              - api_url: 'https://api.telegram.org'
                bot_token_file: /etc/alertmanager/secrets/alertmanager-secret-files/telegram-bot-token
                chat_id: -880628191
                send_resolved: true
                message: '{{ template "telegram.default.message" . }}'
      templateFiles:
        telegram.tmpl: |-
          {{ define "telegram.default.message" }}
          {{ if eq .Status "firing" }}
            {{ if eq .CommonLabels.severity "critical" }}&#128308 <b>Alert:</b> {{ .CommonLabels.alertname }}
            {{ else if eq .CommonLabels.severity "warning" }}&#128992 <b>Alert:</b> {{ .CommonLabels.alertname }}
            {{ else }}&#9898 <b>Alert:</b> {{ .CommonLabels.alertname }}
            {{ end }}
          <b>Status:</b> &#x1F525 FIRING
          <b>Severity:</b> {{ if eq .CommonLabels.severity "critical" }}&#128308 <i>{{ .CommonLabels.severity | title }}</i>
            {{ else if eq .CommonLabels.severity "warning" }}&#128992 <i>{{ .CommonLabels.severity | title }}</i>
            {{ else }}&#9898 <i>{{ .CommonLabels.severity | title }}</i>
            {{ end }}
          {{ else if eq .Status "resolved" }}
            {{ if eq .CommonLabels.severity "critical" }}&#128994 <b>Alert:</b> {{ .CommonLabels.alertname }}
            {{ else if eq .CommonLabels.severity "warning" }}&#128994 <b>Alert:</b> {{ .CommonLabels.alertname }}
            {{ else }}&#9898 <b>Alert:</b> {{ .CommonLabels.alertname }}
            {{ end }}
          <b>Status:</b> &#x2705 RESOLVED
          <b>Severity:</b> {{ if eq .CommonLabels.severity "critical" }}&#128994 <i>{{ .CommonLabels.severity | title }}</i>
            {{ else if eq .CommonLabels.severity "warning" }}&#128994 <i>{{ .CommonLabels.severity | title }}</i>
            {{ else }}&#9898 <i>{{ .CommonLabels.severity | title }}</i>
            {{ end }}
          {{ end }}
          {{- range .Alerts }}
          {{ if .Labels.instance }}<b>Instance:</b> {{ .Labels.instance }}{{ end }}
          {{ if .Annotations.summary }}<b>Summary:</b> {{ .Annotations.summary }}{{ end }}
          {{ if .Annotations.description }}<b>Description:</b> {{ .Annotations.description }}{{ end }}
          {{ end -}}
          {{ end }}
      route:
        main:
          enabled: true
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          hostnames:
            - alertmanager.192.168.31.10.sslip.io
          parentRefs:
            - name: cilium-gateway-monitoring
              namespace: monitoring
          matches:
            - path:
                type: PathPrefix
                value: /
      alertmanagerSpec:
        secrets:
          - alertmanager-secret-files
        replicas: 3
        podAntiAffinity: "hard"
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 50Mi
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
    prometheus:
      route:
        main:
          enabled: true
          apiVersion: gateway.networking.k8s.io/v1
          kind: HTTPRoute
          hostnames:
            - prometheus.192.168.31.10.sslip.io
          parentRefs:
            - name: cilium-gateway-monitoring
              namespace: monitoring
          matches:
            - path:
                type: PathPrefix
                value: /
      prometheusSpec:
        additionalScrapeConfigs:
          - job_name: 'haproxy-external'
            static_configs:
              - targets:
                  - 192.168.31.20:7000  
                  - 192.168.31.21:7000  
                  - 192.168.31.22:7000
            scheme: http
        secrets:
          - etcd-client-cert
        replicas: 2
        podAntiAffinity: "hard"
        retention: 7d
        retentionSize: 5GB
        serviceMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        ignoreNamespaceSelectors: true
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 400m
            memory: 1000Mi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
    prometheusOperator:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
    kubeControllerManager:
      enabled: true
      serviceMonitor:
        enabled: true
        https: true  
        insecureSkipVerify: true
    kubeScheduler:
      enabled: true
      serviceMonitor:
        enabled: true
        https: true  
        insecureSkipVerify: true
    kubeEtcd:
      enabled: true
      endpoints:
       - 192.168.31.20
       - 192.168.31.21
       - 192.168.31.22
      service:
        enabled: true
        port: 2379
        targetPort: 2379
      serviceMonitor:
        enabled: true
        scheme: https
        insecureSkipVerify: false
        caFile: /etc/prometheus/secrets/etcd-client-cert/etcd-ca.crt
        certFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.crt
        keyFile: /etc/prometheus/secrets/etcd-client-cert/healthcheck-client.key
    kubeProxy:
      enabled: false
    kube-state-metrics:
      enabled: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
    prometheus-node-exporter:
      enabled: true
      extraArgs:
        - --collector.textfile.directory=/var/lib/node_exporter/textfile_collector
        - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
        - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|erofs)$
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 400m
          memory: 128Mi
      extraVolumes:
      - name: textfilecollector
        hostPath:
          path:  /opt/node_exporter/textfile_collector
      extraVolumeMounts:
      - mountPath: /var/lib/node_exporter/textfile_collector
        name: textfilecollector
        readOnly: true
  valuesFrom:
    - kind: Secret
      name: prometheus-stack-credentials
      valuesKey: grafana_admin_password
      targetPath: grafana.adminPassword
      optional: false
