---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kubereboot
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://kubereboot.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kured
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kubereboot
      version: 5.11.0
  interval: 30m0s
  install:
    createNamespace: true
  releaseName: kured
  targetNamespace: kured
  values:
    configuration:
      concurrency: 1
      rebootDays: [su,sa]
      startTime: "10:00"
      endTime: "19:00"
      timeZone: "Asia/Yekaterinburg"
      useRebootSentinelHostPath: true
      rebootMethod: "signal"
      rebootSentinel: "/var/run/reboot-required.pkgs"
    containerSecurityContext:
      privileged: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - CAP_KILL
        drop:
        - '*'
    nodeSelector:
      kubernetes.io/os: linux
    resources:
      limits:
        memory: 256Gi
        cpu: 200m
      requests:
        cpu: 100m
        memory: 128Mi
