---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sealed-secrets.yaml
  - kube-prometheus-stack.yaml
  - ingress-nginx.yaml
  - loki.yaml
  - fluent-bit.yaml
  - metrics-server.yaml
  - vertical-pod-autoscaler.yaml
#  - node-problem-detector.yaml
#  - kyverno.yaml
