---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfd
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nfd
      version: 0.18.1
  interval: 30m0s
  install:
    createNamespace: true
  releaseName: node-feature-discovery
  targetNamespace: nfd
  values:
    master:
      enable: true
      replicaCount: 1
      resources:
        limits:
          memory: 256Gi
          cpu: 200m
        requests:
          cpu: 100m
          memory: 128Mi
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "node-role.kubernetes.io/control-plane"
                    operator: In
                    values: [""]
    gc:
      enable: true
      replicaCount: 1
      interval: 1h
      resources:
        limits:
          memory: 256Gi
          cpu: 20m
        requests:
          cpu: 10m
          memory: 128Mi
    worker:
      enable: true
      resources:
        limits:
          cpu: 10m
          memory: 128Mi
        requests:
          cpu: 5m
          memory: 64Mi
      config:
        core:
          sources: ["custom"]
        sources:
          custom:
            - name: "nvme detection"
              labels:
                "feature.node.kubernetes.io/storage-nvme.present": "true"
              matchFeatures:
                - feature: storage.block
                  matchExpressions:
                    name: {op: InRegexp, value: ["^nvme"]}
