---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfd
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: flux-system
spec:
  chart:
    spec:
      chart: node-feature-discovery
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nfd
      version: 0.18.3
  interval: 30m0s
  install:
    createNamespace: true
  releaseName: node-feature-discovery
  targetNamespace: nfd
  values:
    master:
      enable: true
#      extraArgs: 
#        - "-v=2"
      replicaCount: 1
      resources:
        limits:
          memory: 256Gi
          cpu: 200m
        requests:
          cpu: 100m
          memory: 128Mi
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: "node-role.kubernetes.io/control-plane"
                    operator: In
                    values: [""]
    gc:
      enable: true
      replicaCount: 1
      interval: 1h
      resources:
        limits:
          memory: 256Gi
          cpu: 20m
        requests:
          cpu: 10m
          memory: 128Mi
    worker:
      enable: true
      resources:
        limits:
          cpu: 10m
          memory: 128Mi
        requests:
          cpu: 5m
          memory: 64Mi
      config:
        core:
          sleepInterval: 60s
          labelSources: ["custom"]
        sources:
          custom:
            - name: "nvme detection"
              labels:
                "feature.node.kubernetes.io/storage-nvme": "true"
              matchFeatures:
                - feature: storage.block
                  matchExpressions:
                    name: {op: InRegexp, value: ["^nvme"]}
            - name: "network interface speeds"  
              labelsTemplate: |  
                {{ range .network.device }}network-{{ .name }}-speed={{ .speed }}  
                {{ end }}  
              matchFeatures:  
                - feature: network.device  
                  matchExpressions:  
                    operstate: {op: In, value: ["up"]}
            - name: "1G network interface"
              labels:
                "feature.node.kubernetes.io/network-speed-1g": "true"
              matchFeatures:
                - feature: network.device
                  matchExpressions:
                    name: {op: In, value: ["eth0"]}
                    speed: {op: In, value: ["1000"]}
                    operstate: {op: In, value: ["up"]}
            - name: "nfd built-in cpu-model labels"  
              labelsTemplate: |  
                {{ range .cpu.model }}cpu-model.{{ .Name }}={{ .Value }}  
                {{ end }}  
              matchFeatures:  
                - feature: cpu.model  
                  matchName:  
                    op: Exists
            - name: "intel cpu"  
              labels:  
                "feature.node.kubernetes.io/cpu-intel": "true"  
              matchFeatures:  
                - feature: cpu.model  
                  matchExpressions:  
                    vendor_id: {op: In, value: ["Intel"]}
            - name: "amd cpu"  
              labels:  
                "feature.node.kubernetes.io/cpu-amd": "true"  
              matchFeatures:  
                - feature: cpu.model  
                  matchExpressions:  
                    vendor_id: {op: In, value: ["AMD"]}
            - name: "arm cpu"  
              labels:  
                "feature.node.kubernetes.io/cpu-arm": "true"  
              matchFeatures:  
                - feature: cpu.model  
                  matchExpressions:  
                    vendor_id: {op: In, value: ["ARM"]}
