---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stevehipwell
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://stevehipwell.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vertical-pod-autoscaler
  namespace: flux-system
spec:
  chart:
    spec:
      chart: vertical-pod-autoscaler
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: stevehipwell
      version: 1.10.1
  install:
    createNamespace: true
  dependsOn:
    - name: metrics-server
  interval: 30m0s
  releaseName: vertical-pod-autoscaler
  targetNamespace: vertical-pod-autoscaler
  values:
    admissionController:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      extraArgs: 
        - "--feature-gates=InPlaceOrRecreate=true"
    recommender:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      extraArgs:
        - "--humanize-memory=true"
        - "--round-cpu-millicores=50"
    updater:
      replicas: 1
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
      extraArgs:
        - "--feature-gates=InPlaceOrRecreate=true"
