---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-default-secrets
spec:
  generateExisting: true
  rules:
    - name: clone-secrets
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              names:
                - default
                - kube-system
                - kube-public
                - kube-node-lease
                - cilium-secrets
                - kyverno
      generate:
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        cloneList:
          namespace: default
          kinds:
            - v1/Secret
          selector:
            matchLabels:
              sync: "true"
