---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-deploy
  namespace: flux-system
spec:
  dependsOn:
    - name: manifests-post-deploy
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/deploy"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
