---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: manifests
  namespace: flux-system
spec:
  dependsOn:
    - name: apps
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./apps/deploy/manifests"
  interval: 60m
  timeout: 5m
  prune: true
  wait: true
