---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux/alertmanager.yaml
  - ./nfd/nvme-device-rule.yaml
  - ./prometheus/hardware-temperature-rule.yaml
  - ./prometheus/cilium-gateway-monitoring.yaml
