---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./flux/alertmanager.yaml
  - ./cert-manager/selfsigned-bootstrap.yaml
  - ./cert-manager/internal-root-ca.yaml
  - ./cert-manager/ca-issuer.yaml
  - ./nfd/nvme-device-rule.yaml
  - ./nfd/arm64-scaling-governor.yaml
  - ./prometheus/hardware-temperature-rule.yaml
  - ./prometheus/certificate-expiration-rule.yaml
  - ./prometheus/kubecert-expiration-rule.yaml
  - ./prometheus/monitoring-gateway-cert.yaml  
  - ./prometheus/monitoring-gateway.yaml
  - ./prometheus/grafana-dashboard-haproxy.yaml
  - ./system-upgrade-controller/upgrade_plan.yaml
  - ./kyverno/generate-vpa-resource.yaml
  - ./kyverno/clone-default-secrets.yaml
