---
- name: Configure APT proxy.
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/95proxy
    owner: root
    group: root
    mode: '0644'
    content: |
      Acquire::http::Proxy "{{ proxy_address }}";
      Acquire::https::Proxy "{{ proxy_address }}";
      Acquire::socks::Proxy "{{ proxy_address }}";
  when:
    - proxy_address is defined
    - proxy_address | length > 0

- name: Remove APT proxy configuration.
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/95proxy
    state: absent
  when:
    - proxy_address is not defined or proxy_address | length == 0
