---
- name: Apply other sysctl parameters.
  ansible.posix.sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: true
    state: present
    reload: true
  with_dict: '{{ sysctl_config }}'
  ignore_errors: true

- name: Create unattended-upgrades directory.
  ansible.builtin.file:
    path: "/etc/apt/apt.conf.d/50unattended-upgrades.d"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Ensure unattended-upgrades blacklists kernel packages.
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades.d/disable-kernel-upgrades
    content: |
      // Added by Ansible to prevent automatic kernel upgrades
      Unattended-Upgrade::Package-Blacklist {
          "linux-image-raspi";
          "linux-image";
          "linux-headers";
          "linux-modules";
      };
    owner: root
    group: root
    mode: '0644'

- name: Configure journald.
  ansible.builtin.lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "^SystemMaxUse"
    line: "SystemMaxUse=100M"
    backup: true
  notify: Restart journald.

- name: Set LOGINTERVAL for atop.
  ansible.builtin.lineinfile:
    path: /etc/default/atop
    regexp: '^LOGINTERVAL='
    line: 'LOGINTERVAL=60'
    backup: true
  notify: Restart atop.

  # IRQ affinity

- name: IRQ affinity.
  when:
    - irq_affinity | default(false) | bool
  block:
    - name: Write IRQ affinity configuration.
      ansible.builtin.template:
        src: irq-affinity.service.j2
        dest: "/etc/systemd/system/irq-affinity.service"
        owner: root
        mode: '0644'
        backup: true
      notify: Reload systemd.

    - name: Enable and start the IRQ affinity service.
      ansible.builtin.systemd_service:
        name: irq-affinity
        state: started
        enabled: true
