---
# 1
- name: Creates directory.
  ansible.builtin.file:
    path: /etc/kubernetes/node-feature-discovery/features.d
    state: directory
    mode: '0755'
    owner: root

- name: Copy srcipt from variable.
  ansible.builtin.copy:
    content: |
      #!/bin/bash
      
      GOVERNOR=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor 2>/dev/null || echo "unknown")
      echo "cpu.scaling_governor=$GOVERNOR" > /etc/kubernetes/node-feature-discovery/features.d/scaling-governor.conf
    dest: /usr/local/bin/update-scaling-governor.sh
    mode: '0755'
    owner: root

- name: Get file status.
  ansible.builtin.stat:
    path: /usr/local/bin/update-scaling-governor.sh
  register: nfd_file_check_result

- name: Schedule a script.
  ansible.builtin.cron:
    name: "update-scaling-governor.sh"
    user: root
    minute: "0"
    hour: "*/6"
    job: "/usr/local/bin/update-scaling-governor.sh"
    state: present
  when: nfd_file_check_result.stat.exists

# 2

- name: Creates directory.
  ansible.builtin.file:
    path: /opt/node_exporter/textfile_collector
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"

- name: Copy config from variable.
  ansible.builtin.copy:
    content: |
      #!/bin/bash  

      COLLECTOR_TEXTFILE=/opt/node_exporter/textfile_collector/reboot.prom

      if [ -f /var/run/reboot-required ] || [ -f /var/run/reboot-required.pkgs ]; then  
          echo -e "# HELP node_reboot_required Node reboot is required for software updates.\n# TYPE node_reboot_required gauge\nnode_reboot_required 1" > $COLLECTOR_TEXTFILE
      else  
          echo -e "# HELP node_reboot_required Node reboot is required for software updates.\n# TYPE node_reboot_required gauge\nnode_reboot_required 0" > $COLLECTOR_TEXTFILE
      fi
    dest: /usr/local/bin/reboot_required.sh
    mode: '0755'

- name: Get file status.
  ansible.builtin.stat:
    path: /usr/local/bin/reboot_required.sh
  register: prom_file_check_result

- name: Schedule a script.
  ansible.builtin.cron:
    name: "reboot.prom"
    user: "{{ ansible_user }}"
    minute: "0"
    hour: "*"
    job: "/usr/local/bin/reboot_required.sh"
    state: present
  when: prom_file_check_result.stat.exists
