---
- name: Check etcd binary exist.
  ansible.builtin.stat:
    path: "{{ bin_dir }}/etcd"
  register: etcd_check

- name: Download etcd.
  ansible.builtin.unarchive:
    src: https://github.com/etcd-io/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}.tar.gz
    dest: /tmp
    remote_src: true
    mode: '0755'
  when: not etcd_check.stat.exists

- name: Copy etcd binaries to /usr/local/bin.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ bin_dir }}"
    remote_src: true
    mode: '0755'
  loop:
    - "/tmp/etcd-v{{ etcd_version }}-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/etcd"
    - "/tmp/etcd-v{{ etcd_version }}-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/etcdctl"
    - "/tmp/etcd-v{{ etcd_version }}-linux-{{ 'amd64' if ansible_architecture == 'x86_64' else 'arm64' }}/etcdutl"
  when: not etcd_check.stat.exists

- name: Copy the etcd systemd unit file.
  ansible.builtin.template:
    src: etcd.service.j2
    dest: /etc/systemd/system/etcd.service
    mode: '0644'

- name: Ensure etcd is running and enabled at boot.
  ansible.builtin.systemd_service:
    name: etcd
    state: started
    daemon_reload: true
    enabled: true
