---
- name: Make haproxy directory.
  ansible.builtin.file:
    path: "{{ haproxy_config_dir }}"
    state: directory
    mode: '0755'
    owner: root

- name: Write haproxy configuration.
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_dir }}/haproxy.cfg"
    owner: root
    mode: '0644'
    backup: true

- name: Write static pod.
  ansible.builtin.template:
    src: haproxy.manifest.j2
    dest: "{{ kube_manifest_dir }}/haproxy.yaml"
    mode: '0600'
