---
- name: Make directory.
  ansible.builtin.file:
    path: "/etc/systemd/system/kubelet.service.d"
    state: directory
    mode: '0755'
    owner: root

- name: Write kubelet systemd init file.
  ansible.builtin.template:
    src: "kubelet-override.conf.j2"
    dest: "/etc/systemd/system/kubelet.service.d/override.conf"
    backup: true
    mode: '0644'
    owner: root
  notify: Reload systemd.

- name: Create kube.slice systemd unit.
  ansible.builtin.copy:
    dest: "/etc/systemd/system/kube.slice"
    owner: root
    group: root
    mode: '0644'
    content: |
      [Unit]
      Description=Kubernetes Slice

      [Slice]
  when: kube_reserved_cgroups is defined
  notify: Reload systemd.

- name: Check kube.slice systemd unit exist.
  ansible.builtin.stat:
    path: "/etc/systemd/system/kube.slice"
  register: kube_slice_check

- name: Remove kube.slice systemd unit.
  ansible.builtin.file:
    path: "/etc/systemd/system/kube.slice"
    state: absent
  when: 
    - kube_slice_check.stat.exists
    - kube_reserved_cgroups is not defined
  notify: Reload systemd.
